name: GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Project
      run: |
        mkdir public
        echo "<html><body><h1>My GitHub Page</h1></body></html>" > public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
